[package]
name = "gen_map"
version = "0.2.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["Izagawd <theizaboss@gmail.com>"]
keywords = ["generational", "slotmap", "arena", "handle", "no-std"]
categories = ["memory-management", "data-structures", "no-std"]
license = "MIT"
repository = "https://github.com/izagawd/gen_map"
readme = "README.md"
description = "This crate provides customizable generational maps."

[features]
default = ["alloc"]
alloc = []
arrayvec = ["dep:arrayvec"]
smallvec = ["dep:smallvec"]

[dependencies]
arrayvec = { version = "0.7", default-features = false, optional = true }
smallvec = { version = "2.0.0-beta.1", features = [], optional = true }
